/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.Math;
/**
 *
 * @author Zeyad El-banna
 */

public class FlightList extends javax.swing.JFrame {

    /**
     * Creates new form FlightList
     */
    public FlightList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        s = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fno = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1430, 830));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No", "From ", "To", "Date", "Time", "Airport", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 1210, 220));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 110, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 650, 100, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Source");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, 40));

        s.setForeground(new java.awt.Color(102, 102, 102));
        s.setText("Search By Source");
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 260, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 100, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Flight List");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 450, 50));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 35)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 20, -1));

        d.setForeground(new java.awt.Color(102, 102, 102));
        d.setText("Search by Distination");
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 260, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Distination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Flight no.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 90, 30));

        fno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "22", "14", "36" }));
        getContentPane().add(fno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 100, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economic", "Bussness", "First" }));
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 100, 30));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Type of Class");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 130, -1));

        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setText("Enter your Email");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/ty.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try {
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              String url="jdbc:sqlserver://ZEYADELBANNA:1433;DatabaseName=Airlines Booking App;integratedSecurity=true;encrypt=true;trustServerCertificate=true;";
              Connection con = DriverManager.getConnection(url); 
               String source = s.getText();
              String distination = d.getText();
              String sql = "select * from flight_schedule as f, AirFare as a , Route as r where r.Rtid = a.route and f.netfare = a.AFid and r.source=? and r.destination=? ;  ";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1,source );
              pst.setString(2,distination );
              ResultSet rs = pst.executeQuery();
            
             
                 if(rs.next())
               {
                  do
                  {
                       String flightn , s , d , date , time , aname , tprice ;
                       flightn = rs.getString(1);
                       s = rs.getString(12);
                       d = rs.getString(13);
                       date = rs.getString(2);
                       time = rs.getString(3);
                       aname = rs.getString(11);
                       tprice = rs.getString(8);
                       String DBdata[] ={ flightn , s , d ,date , time , aname , tprice};
                       DefaultTableModel tb = (DefaultTableModel)t1.getModel();
                       tb.addRow(DBdata);
                  }  while(rs.next());   
               }
               con.close();
             
       } 
       catch (Exception e ) 
       {
            JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            dispose();
             Home f2 = new Home();
             f2.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         try {
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              String url="jdbc:sqlserver://ZEYADELBANNA:1433;DatabaseName=Airlines Booking App;integratedSecurity=true;encrypt=true;trustServerCertificate=true;";
              Connection con = DriverManager.getConnection(url); 
             int tid = (int)(Math.random()*100)+5;
             int d = (int)(Math.random()*25)+5;
             int m = (int)(Math.random()*9)+2;
             int y = 2023;
             String ddate = Integer.toString(d);
             String mdate = Integer.toString(m);
             String ydate = Integer.toString(y);
             String book = ddate+"-"+mdate+"-"+ydate;
             String flno = (String) fno.getSelectedItem();
             String t = (String) type.getSelectedItem();
             String dis = "154";
             String chrg = "17";
             String dep=" " ;
             DefaultTableModel tb = (DefaultTableModel)t1.getModel();
             for(int i = 0 ; i< tb.getRowCount(); i++)
             {
                    if(((String)tb.getValueAt(i, 0)).equals(flno))
                    {
                        dep = (String)tb.getValueAt(i, 3);
                        break;
                    } 
             }
              int pid = (int)(Math.random()*150)+5;
              String pasid = Integer.toString(pid);
             String email = username.getText();
             String sql = "insert into passengers values ('"+pasid+"','" +email+"');insert into transactions values ('"+tid+"','" +book+"','"+dep+"','"+pasid+"','"+flno+"','"+t+"','"+chrg+"','"+dis+"');";
             PreparedStatement pst = con.prepareStatement(sql);
             pst.executeQuery();
            
            
       } 
       catch (Exception e ) 
       {
            dispose();
             TicketInfo f2 = new TicketInfo();
             f2.setVisible(true);       
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private javax.swing.JComboBox<String> fno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField s;
    private javax.swing.JTable t1;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
